#!/bin/bash

if [ -z $1 ]; then
  echo 'Profile not set [private/work]'
  exit 1
fi

cp bashrc.bashrc ~/.bashrc
cp vimrc.vimrc ~/.vimrc

if [[ "$1" == "private" ]]; then
  cp ~/credentials/gitconfig.gitconfig ~/.gitconfig
fi

exit 0
